name: Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Build
      run: |
        export CGO_ENABLED=0
        go build -ldflags "-s -w -X main.Version=${{ steps.get_version.outputs.VERSION }}" \
                 -trimpath -o ./hashcolor \
           ./cmd/hashcolor/main.go

    - name: Package
      run: |
        tar czf ./hashcolor-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz \
            ./examples ./hashcolor ./LICENSE ./README.md

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Hashcolor ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./hashcolor-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz
        asset_name: hashcolor-${{ steps.get_version.outputs.VERSION }}-linux-x86_64.tar.gz
        asset_content_type: application/gzip
